MODEL:
  META_ARCHITECTURE: "DeepFeatureFlow"
  RPN:
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NAME: "Res5ROIHeads"
    NUM_CLASSES: 30
  DFF:
    FRAME_OFFSET_RANGE: [-9, 0]
    KEY_FRAME_DURATION: 10
DATASETS:
  TRAIN: ("ilsvrc_det_train_30classes", "ilsvrc_vid_train_15frames")
  TEST: ("ilsvrc_vid_val_videos",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.001
  STEPS: (40000,)
  MAX_ITER: 60000
INPUT:
  MIN_SIZE_TRAIN: (600,)
  MAX_SIZE_TRAIN: 1000
  MIN_SIZE_TEST: 600
  MAX_SIZE_TEST: 1000
VIS_PERIOD: 500
VERSION: 2
