MODEL:
  FLOW_NET:
    NAME: "FlowNetS"
    PIXEL_MEAN: [0.45, 0.432, 0.411]
    PIXEL_STD: [1, 1, 1]
    NEGATIVE_SLOPE: 0.1
    MULTISCALE_WEIGHTS: [0.005, 0.01, 0.02, 0.08, 0.32]
    FLOW_DIV: 20.0
VERSION: 2