_BASE_: ../../configs/Base-VID-DFF-RCNN-C4.yaml
MODEL:
  WEIGHTS: "KODO://ImageNetPretrained/MSRA/R-101.pkl"
  FLOW_NET:
    NAME: "FlowNetS"
    WEIGHTS: "KODO://FlyingChairsPretrained/Chen-Jianhu/FlowNetS.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
