_BASE_: ../../configs/Base-FlowNet.yaml
MODEL:
  FLOW_NET:
    NAME: "FlowNetS"
SOLVER:
  IMS_PER_BATCH: 32
  BASE_LR: 0.0004
  STEPS: (75000, 100000, 125000)
  MAX_ITER: 150000
  CHECKPOINT_PERIOD: 1250
TEST:
  EVAL_PERIOD: 1000
VIS_PERIOD: 500
