_BASE_: ../../configs/Base-DFF.yaml
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  RESNETS:
    DEPTH: 101
  FLOWNET:
    WEIGHTS: "KODO://FlyingChairsPretrained/JianhuChen/FlowNetS.pkl"
    NAME: "FlowNetS"
