_BASE_: "./Base-RFCN.yaml"
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  BACKBONE:
    FREEZE_AT: 2
  RESNETS:
      DEPTH: 101
  RPN:
    IN_FEATURES: ["res4"]
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NAME: "RFCNROIHeads"
    IN_FEATURES: ["res5"]
    NEW_CONV_CHANNELS: 1024
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_TYPE: "PSROIPool"
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (60000, 80000)
  MAX_ITER: 90000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
VERSION: 2
